### ISSUE TITLE
Change Clock to a struct

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#179]
I think this makes more sense as a struct than a class.

Current idea is to basically copy SFML's layout for the Clock type and pretend that sfClock is our private clock implementation. Either that or create a wrapper function around ClockImpl's getCurrentTime.

**Comment by luke5542** [comment]
I think we could also improve this in a similar manner to #180 by adding support for [Duration](http://dlang.org/phobos/core_time.html#Duration) and by internally using [MonoTime](http://dlang.org/phobos/core_time.html#MonoTime).

My thoughts are that we would bring the clock into D and get rid of Time. I do see one obstacle to this, though, in that Clock is used in multiple places throughout DSFMLC and that might be problematic to remove (though we could possibly leave the DSFMLC clock there while only exposing this new clock in D, or we could just internally use `long`s in a bunch of places to replace clock).

**Comment by Jebbs** [comment]
Clock is used internally in DSFMLC? Can you give me a example?

Also, support for Duration and MonoTime would be interesting, but those use way more precision than is ever used internally. Is there any other reason to use MonoTime other than that's what the standard library uses? Not really sure how Duration functionality could be added.

**Comment by luke5542** [comment]
I first heard about the internal usage of Clock from the [SFML Window Tutorial](http://www.sfml-dev.org/tutorials/2.3/window-window.php#controlling-the-framerate), but if you checkout line 327 in [Window.cpp](https://github.com/Jebbs/DSFMLC/blob/master/src/SFML/Window/Window.cpp) in the `window.display()` function, that's probably the most obvious example. I recall having seen other internal usages of Clock and Time, but I do not remember where they are.

My main reason for using MonoTime is that it's the only monotonic timestamp I've found in the standard library, and SFML itself uses a motonic clock. As for adding Duration support, it would be as simple as returning a Duration object rather than a Time object from methods like `getElapsedTime` and `restart`. The current implementation of Time would disappear all together and we would just instruct people (through the tutorials, for example) to use the `core.time.Duration` in any place that requires a representation of an amount of time.

**Comment by Jebbs** [comment]
Superseded by #199
