### ISSUE TITLE
Make everything structs?

### ISSUE THREAD

**Issue by Jebbs** [Jebbs/DSFML#191]
I was reading some of this thread today: http://forum.dlang.org/thread/aetzsanbypaimljrguzb@forum.dlang.org

Read through it if you want, but basically I was wondering if I should change all classes to structs. This could be helpful by providing more deterministic destruction and would help keep GC usage down (assuming that things don't end up as member of a class).

Polymorphism isn't used that much, so most things could be changed to structs with out much issue. The polymorphism that is used could easily be faked with introspection, for example:

```void draw(Drawable drawable, RenderStates states = RenderStates.Default)```

could be changed to

```
void draw(T)(ref T drawable, RenderStates states = RenderStates.Default)
	if(__traits(hasMember(T,"draw"))
```
Or something like that. 

On the other hand, I like the structure that polymorphism gives us. 

I'll think about it some more and wait for potential replies.

**Comment by aubade** [comment]
I've got two slight hangups about this; The first is that things like Sprite lend themeslves well to class derivation, and the second is that there are significant difficulties in storing heterogeneous template-polymorphic references; for instance the part of my ECS that handles what to draw for an entity in an environment uses a Drawable ref rather than Sprite to allow for any sort of SFML based drawable. 

I also use some hackery with Sound and BlackHole to make for a system that can gracefully handle too many sounds playing; If it's overwhelmed, the sound subsystem hands you an object that No-ops everything rather than a real Sound.

**Comment by Jebbs** [comment]
Perhaps I should still go struct nuts though? As in anything that uses polymorphism can stay as a class, everything else becomes a struct?

That might be a good approach. It would also simplify things in terms of remembering what is a struct and what is a class.

**Comment by Jebbs** [comment]
I think I like that idea. Everything that can be a struct should be a struct. Everything that needs polymorphism should be a class. That is how I will structure the library moving forward.

I'll close this and all other issues related to this (I think there are a couple) and open a new one that describes the change.

**Comment by Jebbs** [comment]
Superseded by #199
