### ISSUE TITLE
The new Duration .total!"seconds" and friends return long not float

### ISSUE THREAD

**Issue by nikibobi** [Jebbs/DSFML#210]
My old code used `.asSeconds` and it returned a float. Now with duration `total!"seconds"` returns a long and if its a fraction I get 0.

**Comment by Jebbs** [comment]
I was worried about that part when we made the change, but we can always change it back if it seems like floats work better than durations. I guess a duration makes it more consistent with other D libraries.

You could always do  `total!"msecs"/1000f`if you need seconds with a floating point value though.

**Comment by luke5542** [comment]
I think the consistency is worth the use of Duration, since it's always possible to use the suggestion from @Jebbs . If this is a problem relating to Clock, then it might be a bit more convenient to add a `getElapsedTime` overload (or name change) that returns a float of the seconds passed.

Also, I notice that there's no current development branch (or next version branch, etc), so it might be advantageous to create another branch for any future changes and leave the master branch alone, except to record major version milestones and version tagging. This could at least allow for development to occur without forcing everyone to stay on the latest version.

**Comment by nikibobi** [comment]
I found a workaround, but I don't like it. I convert Duration to TickDuration and use the to! method like this:
`float dt = to!("seconds", float)(deltaClock.restart().to!TickDuration());`
The problem is TickDuration is deprecated. I don't know why Duration doesn't have a to method.

**Comment by luke5542** [comment]
@nikibobi the suggestion from @Jebbs is a bit cleaner than that while doing exactly the same (having the f after 1000 makes it a float, and division with a float converts the long to a float and returns a float result that shouldn't be 0 unnecessarily).

The problem with Duration having a to method would be in knowing exactly what you want to convert from it. This is why Duration has two methods for this purpose: split and total. The former gets you exclusively the value of that unit, excluding anything larger, while the latter includes the larger units and gives you the sum total (hence the method's name) of those units.

**Comment by nikibobi** [comment]
I think it will be a good idea to add such method to `clock.d` that returns float units. Probably something like this: `float totalf(string units)(Duration duration) { ... }` or a more concrete method like @luke5542 suggested `float getElapsedSeconds() { ... }`

**Comment by Jebbs** [comment]
I think the real issue here was that a large change was made to the API with out a deprecation step. I'll need to make sure this happens in the future.

I'm not sure what the solution is to the issue presented though. It's fairly simple to get the seconds as a floating point value. Do we really need to add a conversion function?

**Comment by Jebbs** [comment]
A possible solution might be to add the Time struct back into DSFML (along with everything that used it) and mark them all as deprecated. I'm trying to get a release out soon since I have a lot of free time this summer, and if the release brings people back to try old projects I don't want things to break.

Alternatively, we could just rip off the band-aid and let things fall how they will, but I like that less.
