### ISSUE TITLE
audio ~>2.4 cannot be satisfied

### ISSUE THREAD

**Issue by joelcnz** [Jebbs/DSFML#270]
On macOS.

Joels-MBP:SpellIt2 joelchristensen$ dub upgrade
Upgrading project in /Users/joelchristensen/jpro/dpro2/SpellIt2
Root package spellit reference dsfml:audio ~>2.4 cannot be satisfied, graphics too.

```
Some dub.json (as follows):
    "dependencies": 
    {
        "dsfml:graphics": "~>2.4",
		"dsfml:audio": "~>2.4"
    }

```

**Comment by Jebbs** [comment]
Although the 2.4 work is in the master branch, it's still being worked on. I believe DUB can grab both tags and branches, so because there's a 2.4 branch (which should be deleted now) you see that there's a 2.4 version available in dub.

I'm not sure what the right thing to do it, but I'm sorry for the confusion.

**Comment by joelcnz** [comment]
No worries.
